user_email_maxlen: 255
user_password_minlen: 6
user_name_maxlen: 50
min_score: 0
varchar_maxlen: 50
login_hidden_value: 1
per_page: 10
gravatar_size: 50
gravatar_default_size: 80
comment_form_rows: "3"
min_birthday: "1940-01-01"
min_pnumber: 0
more_article_num: 10
homepage_article_num: 5
homepage_matches_num: 5
homepage_players_num: 3
zero: 0
homepage_slider_range: 2
limit_number_of_matches: 30
done_pair_value: "Coming undone"
undone_pair_value: "Finished done"
done_value: "done"
undone_value: "undone"
min_matchday: "1990-01-01"
min_score: 0
